
    create table Comuna (
        nroComuna integer not null,
        primary key (nroComuna)
    )

    create table Usuario (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        comuna_nroComuna integer,
        primary key (id)
    )

    alter table Usuario 
        add constraint FK_dsx5mp2qmgrndgohrs4jdc2l4 
        foreign key (comuna_nroComuna) 
        references Comuna
