
    create table Bancos (
        nombre varchar(255),
        id_Poi bigint not null,
        primary key (id_Poi)
    )

    create table Busqueda (
        id_Busqueda integer generated by default as identity (start with 1),
        cantResultados integer not null,
        fecha varbinary(255),
        fraseBuscada varchar(255),
        tiempoBusqueda integer not null,
        id_Terminal integer,
        usuario_id integer,
        primary key (id_Busqueda)
    )

    create table Busqueda_Notificadores (
        id_Busqueda integer not null,
        id bigint not null
    )

    create table Busqueda_POIs (
        id_Busqueda integer not null,
        id_Poi bigint not null
    )

    create table BusquedasPorFecha (
        id bigint not null,
        primary key (id)
    )

    create table CGPES (
        id_Poi bigint not null,
        comuna_nroComuna integer,
        primary key (id_Poi)
    )

    create table Comuna (
        nroComuna integer not null,
        primary key (nroComuna)
    )

    create table DiaAtencion (
        id_diaAtencion bigint generated by default as identity (start with 1),
        dia varchar(255),
        horaApertura integer not null,
        horaCierre integer not null,
        primary key (id_diaAtencion)
    )

    create table Locales (
        nombre varchar(255),
        rubro varchar(255),
        id_Poi bigint not null,
        primary key (id_Poi)
    )

    create table NotificadorDeAdministrador (
        id bigint not null,
        tiempoParaNotificar integer not null,
        primary key (id)
    )

    create table PalabrasClaves (
        palabra_id bigint not null,
        palabrasClaves varchar(255)
    )

    create table Paradas (
        numeroDeLinea varchar(255),
        id_Poi bigint not null,
        primary key (id_Poi)
    )

    create table Pois (
        id_Poi bigint generated by default as identity (start with 1),
        altura varchar(255),
        calle varchar(255),
        coordenadaX double not null,
        coordenadaY double not null,
        toleranciaEnCuadras integer not null,
        posicion_id_Punto integer,
        primary key (id_Poi)
    )

    create table Punto (
        id_Punto integer generated by default as identity (start with 1),
        x double not null,
        y double not null,
        id integer,
        nro_puntos integer,
        primary key (id_Punto)
    )

    create table ReportePorBusqueda (
        id bigint generated by default as identity (start with 1),
        cantidadDeResultados double not null,
        demoraDeBusqueda double not null,
        fraseBuscada varchar(255),
        numeroDeRenglon bigint,
        primary key (id)
    )

    create table ReportePorFecha (
        id bigint generated by default as identity (start with 1),
        cantidadDeBusquedas double not null,
        diaDeLaBusqueda timestamp,
        numDeRenglon bigint,
        primary key (id)
    )

    create table ReportePorTerminal (
        id bigint generated by default as identity (start with 1),
        numeroDeRenglon bigint,
        primary key (id)
    )

    create table ResultadosDeBusquedas (
        id bigint not null,
        primary key (id)
    )

    create table ResultadosPorTerminal (
        id bigint not null,
        primary key (id)
    )

    create table Servicio (
        id_Servicio bigint generated by default as identity (start with 1),
        nombre varchar(255),
        nroServicio bigint,
        primary key (id_Servicio)
    )

    create table Servicio_DiaAtencion (
        id_Servicio bigint not null,
        id_diaAtencion bigint not null
    )

    create table T_RESULTADO_BUSQUEDA (
        CD_BUSQUEDA integer not null,
        QT_RESULTADOS integer,
        CD_TERMINAL integer,
        DC_FRASE_BUSCADA varchar(255),
        TIEMPO_BUSQUEDA integer,
        primary key (CD_BUSQUEDA)
    )

    create table Terminal (
        id_Terminal integer generated by default as identity (start with 1),
        nombreDeTerminal varchar(255),
        primary key (id_Terminal)
    )

    create table Terminal_Notificadores (
        id_Terminal integer not null,
        id bigint not null
    )

    create table Usuarios (
        id integer generated by default as identity (start with 1),
        nombre varchar(255),
        comuna_nroComuna integer,
        primary key (id)
    )

    create table cantidadDeResultados (
        resultado_id bigint not null,
        cantResultados double
    )

    alter table Bancos 
        add constraint FK_nqdaawv1tjjvg4tbgxsgmqyui 
        foreign key (id_Poi) 
        references Pois

    alter table Busqueda 
        add constraint FK_51hocrkuji4ro4akkuw0ilm23 
        foreign key (id_Terminal) 
        references Terminal

    alter table Busqueda 
        add constraint FK_kst63qirf9cu9g82an666to5r 
        foreign key (usuario_id) 
        references Usuarios

    alter table Busqueda_Notificadores 
        add constraint FK_lvwueowdbt9y8lmfvu048eukh 
        foreign key (id_Busqueda) 
        references Busqueda

    alter table Busqueda_POIs 
        add constraint FK_arf6fel9wi8itkhhcqbmhy6kv 
        foreign key (id_Poi) 
        references Pois

    alter table Busqueda_POIs 
        add constraint FK_39v18h7f5isn8d7a58617mefh 
        foreign key (id_Busqueda) 
        references Busqueda

    alter table CGPES 
        add constraint FK_dy5mq3cjmubkuokfgfgv7ll39 
        foreign key (comuna_nroComuna) 
        references Comuna

    alter table CGPES 
        add constraint FK_y1jddmvn76jtm3yl2j74b8s4 
        foreign key (id_Poi) 
        references Pois

    alter table DiaAtencion 
        add constraint FK_o87pgquhnpx23x01ugfw4bvne 
        foreign key (id_diaAtencion) 
        references Pois

    alter table Locales 
        add constraint FK_iduoahsmp2820s4wt4va3dh11 
        foreign key (id_Poi) 
        references Pois

    alter table PalabrasClaves 
        add constraint FK_lfgbcs1q435ixn8vwtoo3pqnr 
        foreign key (palabra_id) 
        references Locales

    alter table Paradas 
        add constraint FK_br0colbhjj7ihibkg2cler3uc 
        foreign key (id_Poi) 
        references Pois

    alter table Pois 
        add constraint FK_1xx5ug2yng5t8udw0s4ik7nkb 
        foreign key (posicion_id_Punto) 
        references Punto

    alter table Punto 
        add constraint FK_4k35qm17phvme3rdna1dt30jm 
        foreign key (id) 
        references Comuna

    alter table ReportePorBusqueda 
        add constraint FK_avpeivm398pskns974pdpluqm 
        foreign key (numeroDeRenglon) 
        references ResultadosDeBusquedas

    alter table ReportePorFecha 
        add constraint FK_i9ijtgb3ay36gch872ixb9t6d 
        foreign key (numDeRenglon) 
        references BusquedasPorFecha

    alter table ReportePorTerminal 
        add constraint FK_nr4p38shiw66ud8kmmrr9xm2e 
        foreign key (numeroDeRenglon) 
        references ResultadosPorTerminal

    alter table Servicio 
        add constraint FK_piv7srmwlbw1p3h0f0n4jso26 
        foreign key (nroServicio) 
        references CGPES

    alter table Servicio_DiaAtencion 
        add constraint FK_9h4mh5w2wf9h871lrkim0i224 
        foreign key (id_diaAtencion) 
        references DiaAtencion

    alter table Servicio_DiaAtencion 
        add constraint FK_qpd5cta3qn77g9txaw2v3mlxw 
        foreign key (id_Servicio) 
        references Servicio

    alter table Terminal_Notificadores 
        add constraint FK_hug61cyei8kq0l3tedhcybo4x 
        foreign key (id_Terminal) 
        references Terminal

    alter table Usuarios 
        add constraint FK_2hinp9iqdk4wwr0tfxa15nn7y 
        foreign key (comuna_nroComuna) 
        references Comuna

    alter table cantidadDeResultados 
        add constraint FK_it23gnlgqoj7f48788ceh61gy 
        foreign key (resultado_id) 
        references ReportePorTerminal

    create table hibernate_sequences (
         sequence_name varchar(255),
         sequence_next_hi_value integer 
    )
